baseURL: "https://www.julienbouquet.me/"
languageCode: "en-us"
title: Julien Bouquet - Personal Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
uglyURLs: true

minify:
  disableXML: true
  minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Julien Bouquet - Personal Blog
    description: "Julien Bouquet - Personal Blog"
    keywords: [Blog, Portfolio, PaperMod]
    author: Me
    
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false


    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        #favicon: "<link / abs url>"
        #favicon16x16: "<link / abs url>"
        #favicon32x32: "<link / abs url>"
        #apple_touch_icon: "<link / abs url>"
        #safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
          - name: Posts
            url: posts
          - name: Tags
            url: tags

    # home-info mode
    homeInfoParams:
        Title: "Julien Bouquet"
        Content: 
          Welcome to my blog,

          I’m a French developer, 
          I create this blog to share my experience and some best practices on development. 
          I like Open Source, I love contributing and have contributions on my repositories to learn from other developers.  


    socialIcons:
        - name: twitter
          url: "https://twitter.com/julien-bouquet"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/7143453/julien-bouquet"
        - name: github
          url: "https://github.com/julien-bouquet"

    # analytics:
        # google:
            # SiteVerificationTag: "XYZabc"
        # bing:
            # SiteVerificationTag: "XYZabc"
        # yandex:
            # SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/julien-bouquet/personal-blog/issues"
        Text: "Suggest Changes" # edit text
        appendFilePath: false # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: posts
      name: posts
      weight: 20
      
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai