# For release build - release that - Github action tag and deploy it on Google Cloud Storage
name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          # Token is used to push on main branch
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'

      - name: Build
        run: hugo --minify

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2.6.0
        with:
          semantic_version: 17.3.7
          extra_plugins: |
            @semantic-release/commit-analyzer@8.0.1
            @semantic-release/release-notes-generator@9.0.1
            @semantic-release/changelog@5.0.1
            @semantic-release/github@7.2.0
            @semantic-release/exec@5.0.0
            @semantic-release/git@9.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Pupblic dir on Google Cloud Storage
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: public
          destination: ${{ secrets.BUCKET }}
          glob: "*"
          gzip: false
          parent: false
